name: PR Check - Frontend

on:
  pull_request:
    branches:
      - master

jobs:
  check-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm ci

      - name: Verificación básica
        run: echo "Pull Request detectado en el frontend ✔️"
